version: 2.0
jobs:
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: ./compile_bit.sh -d
      - run: ./bit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_6
      - build_gcc_latest
